# --- Frontend build (Vite) ---
# Vite inlines import.meta.env.VITE_* at build time. Docker does not read your .env file
# unless we pass each variable in as ARG/ENV before `npm run build`.
#
# Railway: add the same variable names in the service Variables tab, then redeploy.
# For API + UI on one host (this image runs Express + static dist), set
# VITE_PDF_API_BASE_URL to empty so the client calls /api/... on the same origin.
# For local dev (Vite on :5173, API on :3001), use http://localhost:3001 instead.
#
# See src/services/airtable.js and related imports for usage.

FROM node:20-alpine AS builder

WORKDIR /app

# --- All VITE_* keys referenced in the client (keep in sync when adding new ones) ---
ARG VITE_AIRTABLE_BASE_ID
ARG VITE_AIRTABLE_API_KEY
ARG VITE_PRODUCTION_PROJECTS_TABLE_ID
ARG VITE_MATERIALS_TABLE_ID
ARG VITE_SUPPLIERS_TABLE_ID
ARG VITE_AIRTABLE_TABLE_ID
ARG VITE_AIRTABLE_TABLE_NAME
ARG VITE_SUPPLIER_ORDERS_TABLE_ID
ARG VITE_SUPPLIER_ORDER_LINES_TABLE_ID
ARG VITE_PRODUCTION_PROJECTS_FIELD
ARG VITE_PRODUCTION_PROJECTS_CLIENT_FIELD
ARG VITE_MATERIALS_DISPLAY_FIELD
ARG VITE_MATERIALS_FIELD
ARG VITE_SUPPLIERS_FIELD
ARG VITE_CUSTOMERS_TABLE_ID
ARG VITE_QUOTE_CUSTOMERS_TABLE_ID
ARG VITE_CONTACTS_TABLE_ID
ARG VITE_QUOTE_CONTACTS_TABLE_ID
ARG VITE_QUOTE_CUSTOMER_NAME_FIELD
ARG VITE_QUOTE_CREATED_BY_TABLE_ID
ARG VITE_QUOTE_EMPLOYEE_NAME_FIELD
ARG VITE_CUSTOMER_CONTACTS_LINK_FIELD
ARG VITE_CONTACT_NAME_FIELD
ARG VITE_CONTACT_EMAIL_FIELD
ARG VITE_CONTACT_PHONE_FIELD
ARG VITE_PDF_API_BASE_URL

ENV VITE_AIRTABLE_BASE_ID=$VITE_AIRTABLE_BASE_ID
ENV VITE_AIRTABLE_API_KEY=$VITE_AIRTABLE_API_KEY
ENV VITE_PRODUCTION_PROJECTS_TABLE_ID=$VITE_PRODUCTION_PROJECTS_TABLE_ID
ENV VITE_MATERIALS_TABLE_ID=$VITE_MATERIALS_TABLE_ID
ENV VITE_SUPPLIERS_TABLE_ID=$VITE_SUPPLIERS_TABLE_ID
ENV VITE_AIRTABLE_TABLE_ID=$VITE_AIRTABLE_TABLE_ID
ENV VITE_AIRTABLE_TABLE_NAME=$VITE_AIRTABLE_TABLE_NAME
ENV VITE_SUPPLIER_ORDERS_TABLE_ID=$VITE_SUPPLIER_ORDERS_TABLE_ID
ENV VITE_SUPPLIER_ORDER_LINES_TABLE_ID=$VITE_SUPPLIER_ORDER_LINES_TABLE_ID
ENV VITE_PRODUCTION_PROJECTS_FIELD=$VITE_PRODUCTION_PROJECTS_FIELD
ENV VITE_PRODUCTION_PROJECTS_CLIENT_FIELD=$VITE_PRODUCTION_PROJECTS_CLIENT_FIELD
ENV VITE_MATERIALS_DISPLAY_FIELD=$VITE_MATERIALS_DISPLAY_FIELD
ENV VITE_MATERIALS_FIELD=$VITE_MATERIALS_FIELD
ENV VITE_SUPPLIERS_FIELD=$VITE_SUPPLIERS_FIELD
ENV VITE_CUSTOMERS_TABLE_ID=$VITE_CUSTOMERS_TABLE_ID
ENV VITE_QUOTE_CUSTOMERS_TABLE_ID=$VITE_QUOTE_CUSTOMERS_TABLE_ID
ENV VITE_CONTACTS_TABLE_ID=$VITE_CONTACTS_TABLE_ID
ENV VITE_QUOTE_CONTACTS_TABLE_ID=$VITE_QUOTE_CONTACTS_TABLE_ID
ENV VITE_QUOTE_CUSTOMER_NAME_FIELD=$VITE_QUOTE_CUSTOMER_NAME_FIELD
ENV VITE_QUOTE_CREATED_BY_TABLE_ID=$VITE_QUOTE_CREATED_BY_TABLE_ID
ENV VITE_QUOTE_EMPLOYEE_NAME_FIELD=$VITE_QUOTE_EMPLOYEE_NAME_FIELD
ENV VITE_CUSTOMER_CONTACTS_LINK_FIELD=$VITE_CUSTOMER_CONTACTS_LINK_FIELD
ENV VITE_CONTACT_NAME_FIELD=$VITE_CONTACT_NAME_FIELD
ENV VITE_CONTACT_EMAIL_FIELD=$VITE_CONTACT_EMAIL_FIELD
ENV VITE_CONTACT_PHONE_FIELD=$VITE_CONTACT_PHONE_FIELD
ENV VITE_PDF_API_BASE_URL=$VITE_PDF_API_BASE_URL

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .
RUN npm run build

# --- Express API + static SPA (same port) ---
FROM node:20-alpine

WORKDIR /app

COPY server/package.json server/package-lock.json* ./server/
RUN cd server && npm ci --omit=dev

COPY server/ ./server/
COPY --from=builder /app/dist ./dist

ENV NODE_ENV=production
ENV PORT=3000
EXPOSE 3000

WORKDIR /app/server

CMD ["node", "index.js"]
