# Build stage
FROM node:20-alpine AS builder

WORKDIR /app

# Build-time args (pass from Railway or your CI as --build-arg)
ARG VITE_AIRTABLE_BASE_ID
ARG VITE_AIRTABLE_API_KEY
ARG VITE_PRODUCTION_PROJECTS_TABLE_ID
ARG VITE_MATERIALS_TABLE_ID
ARG VITE_AIRTABLE_TABLE_ID
ARG VITE_AIRTABLE_TABLE_NAME
ARG VITE_PRODUCTION_PROJECTS_FIELD
ARG VITE_MATERIALS_FIELD

ENV VITE_AIRTABLE_BASE_ID=$VITE_AIRTABLE_BASE_ID
ENV VITE_AIRTABLE_API_KEY=$VITE_AIRTABLE_API_KEY
ENV VITE_PRODUCTION_PROJECTS_TABLE_ID=$VITE_PRODUCTION_PROJECTS_TABLE_ID
ENV VITE_MATERIALS_TABLE_ID=$VITE_MATERIALS_TABLE_ID
ENV VITE_AIRTABLE_TABLE_ID=$VITE_AIRTABLE_TABLE_ID
ENV VITE_AIRTABLE_TABLE_NAME=$VITE_AIRTABLE_TABLE_NAME
ENV VITE_PRODUCTION_PROJECTS_FIELD=$VITE_PRODUCTION_PROJECTS_FIELD
ENV VITE_MATERIALS_FIELD=$VITE_MATERIALS_FIELD

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .
RUN npm run build

# Serve stage
FROM node:20-alpine

WORKDIR /app

RUN npm install -g serve

COPY --from=builder /app/dist ./dist

ENV PORT=3000
EXPOSE 3000

CMD ["sh", "-c", "serve -s dist -l ${PORT}"]
